/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TablerosRouteImport } from './routes/tableros-electricos-industriales'
import { Route as SitemapXmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProyectosRouteImport } from './routes/proyectos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as AutomatizacionRouteImport } from './routes/automatizacion-industrial'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminPopupRouteImport } from './routes/admin.popup'
import { Route as AdminFormulariosRouteImport } from './routes/admin.formularios'
import { Route as AdminConfiguracionRouteImport } from './routes/admin.configuracion'
import { Route as AdminConfianzaRouteImport } from './routes/admin.confianza'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminAdjuntosRouteImport } from './routes/admin.adjuntos'

const TablerosRoute = TablerosRouteImport.update({
  id: '/tableros-electricos-industriales',
  path: '/tableros-electricos-industriales',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosRoute = ProyectosRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomatizacionRoute = AutomatizacionRouteImport.update({
  id: '/automatizacion-industrial',
  path: '/automatizacion-industrial',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPopupRoute = AdminPopupRouteImport.update({
  id: '/popup',
  path: '/popup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormulariosRoute = AdminFormulariosRouteImport.update({
  id: '/formularios',
  path: '/formularios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracionRoute = AdminConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfianzaRoute = AdminConfianzaRouteImport.update({
  id: '/confianza',
  path: '/confianza',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdjuntosRoute = AdminAdjuntosRouteImport.update({
  id: '/adjuntos',
  path: '/adjuntos',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/automatizacion-industrial': typeof AutomatizacionRoute
  '/contacto': typeof ContactoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/proyectos': typeof ProyectosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/servicios': typeof ServiciosRoute
  '/sitemap.xml': typeof SitemapXmlRoute
  '/tableros-electricos-industriales': typeof TablerosRoute
  '/admin/adjuntos': typeof AdminAdjuntosRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/confianza': typeof AdminConfianzaRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/formularios': typeof AdminFormulariosRoute
  '/admin/popup': typeof AdminPopupRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automatizacion-industrial': typeof AutomatizacionRoute
  '/contacto': typeof ContactoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/proyectos': typeof ProyectosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/servicios': typeof ServiciosRoute
  '/sitemap.xml': typeof SitemapXmlRoute
  '/tableros-electricos-industriales': typeof TablerosRoute
  '/admin/adjuntos': typeof AdminAdjuntosRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/confianza': typeof AdminConfianzaRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/formularios': typeof AdminFormulariosRoute
  '/admin/popup': typeof AdminPopupRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/automatizacion-industrial': typeof AutomatizacionRoute
  '/contacto': typeof ContactoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/proyectos': typeof ProyectosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/servicios': typeof ServiciosRoute
  '/sitemap.xml': typeof SitemapXmlRoute
  '/tableros-electricos-industriales': typeof TablerosRoute
  '/admin/adjuntos': typeof AdminAdjuntosRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/confianza': typeof AdminConfianzaRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/formularios': typeof AdminFormulariosRoute
  '/admin/popup': typeof AdminPopupRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/automatizacion-industrial'
    | '/contacto'
    | '/forgot-password'
    | '/login'
    | '/proyectos'
    | '/reset-password'
    | '/servicios'
    | '/sitemap.xml'
    | '/tableros-electricos-industriales'
    | '/admin/adjuntos'
    | '/admin/clientes'
    | '/admin/confianza'
    | '/admin/configuracion'
    | '/admin/formularios'
    | '/admin/popup'
    | '/admin/usuarios'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automatizacion-industrial'
    | '/contacto'
    | '/forgot-password'
    | '/login'
    | '/proyectos'
    | '/reset-password'
    | '/servicios'
    | '/sitemap.xml'
    | '/tableros-electricos-industriales'
    | '/admin/adjuntos'
    | '/admin/clientes'
    | '/admin/confianza'
    | '/admin/configuracion'
    | '/admin/formularios'
    | '/admin/popup'
    | '/admin/usuarios'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/automatizacion-industrial'
    | '/contacto'
    | '/forgot-password'
    | '/login'
    | '/proyectos'
    | '/reset-password'
    | '/servicios'
    | '/sitemap.xml'
    | '/tableros-electricos-industriales'
    | '/admin/adjuntos'
    | '/admin/clientes'
    | '/admin/confianza'
    | '/admin/configuracion'
    | '/admin/formularios'
    | '/admin/popup'
    | '/admin/usuarios'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AutomatizacionRoute: typeof AutomatizacionRoute
  ContactoRoute: typeof ContactoRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ProyectosRoute: typeof ProyectosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServiciosRoute: typeof ServiciosRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  TablerosRoute: typeof TablerosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tableros-electricos-industriales': {
      id: '/tableros-electricos-industriales'
      path: '/tableros-electricos-industriales'
      fullPath: '/tableros-electricos-industriales'
      preLoaderRoute: typeof TablerosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos': {
      id: '/proyectos'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof ProyectosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automatizacion-industrial': {
      id: '/automatizacion-industrial'
      path: '/automatizacion-industrial'
      fullPath: '/automatizacion-industrial'
      preLoaderRoute: typeof AutomatizacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/popup': {
      id: '/admin/popup'
      path: '/popup'
      fullPath: '/admin/popup'
      preLoaderRoute: typeof AdminPopupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/formularios': {
      id: '/admin/formularios'
      path: '/formularios'
      fullPath: '/admin/formularios'
      preLoaderRoute: typeof AdminFormulariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracion': {
      id: '/admin/configuracion'
      path: '/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AdminConfiguracionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/confianza': {
      id: '/admin/confianza'
      path: '/confianza'
      fullPath: '/admin/confianza'
      preLoaderRoute: typeof AdminConfianzaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/adjuntos': {
      id: '/admin/adjuntos'
      path: '/adjuntos'
      fullPath: '/admin/adjuntos'
      preLoaderRoute: typeof AdminAdjuntosRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdjuntosRoute: typeof AdminAdjuntosRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminConfianzaRoute: typeof AdminConfianzaRoute
  AdminConfiguracionRoute: typeof AdminConfiguracionRoute
  AdminFormulariosRoute: typeof AdminFormulariosRoute
  AdminPopupRoute: typeof AdminPopupRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdjuntosRoute: AdminAdjuntosRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminConfianzaRoute: AdminConfianzaRoute,
  AdminConfiguracionRoute: AdminConfiguracionRoute,
  AdminFormulariosRoute: AdminFormulariosRoute,
  AdminPopupRoute: AdminPopupRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AutomatizacionRoute: AutomatizacionRoute,
  ContactoRoute: ContactoRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ProyectosRoute: ProyectosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServiciosRoute: ServiciosRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  TablerosRoute: TablerosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
